FORMAT: 1A
HOST: http://www.google.com

# Bitbloq
Bitbloq is an Arduino IDE designed for children. It allows to program sketches and upload them directly onto the board. The code is constructed connecting blocks that contain programming statements such as if, for, etc. 

# Group Notes
Bitbloq related resources of the **Bitbloq API**

## Blocks [/bitbloq:Block]
### List all Blocks [GET]
+ Response 200 (application/json)

        [{
          "id": 1,
          "name": "aaa",
          "category": "bq"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Block [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
